version: "3"
services:
    nginx:
        build:
            dockerfile: ./docker/Dockerfile
            context: ../
        ports:
            - 8001:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:rw
            - ../website:/var/www/html/:rw
            - ../docker/urls.js:/var/www/html/static/js/urls.js:rw
